baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[taxonomies]
  tag = 'tags'
  campaign = 'campaigns'
  class = 'classes'
  race = 'races'
  background = 'backgrounds'
  alignment = 'alignments'
  gender = 'genders'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
