name = 'dnd-hugo'
license = 'MIT'
licenselink = 'https://github.com/sekthor/dnd-hugo/LICENSE'
description = 'Theme to document DnD Campaigns'

homepage = 'https://github.com/sekthor/dnd-hugo'

demosite = 'https://sekthor.github.io/dnd'

[author]
  name = 'sekthor'
  homepage = 'website'
